export const FETCH_BLOG_REQUEST= "FETCH_BLOG_REQUEST";
export const FETCH_BLOG_SUCCESS= "FETCH_BLOG_SUCCESS";
export const FETCH_BLOG_FAIL= "FETCH_BLOG_FAIL";
export const FETCH_SINGLE_BLOG_REQUEST= "FETCH_SINGLE_BLOG_REQUEST";
export const FETCH_SINGLE_BLOG_SUCCESS= "FETCH_SINGLE_BLOG_SUCCESS";
export const FETCH_SINGLE_BLOG_FAIL= "FETCH_SINGLE_BLOG_FAIL";
export const ADD_BLOG_REQUEST= "ADD_BLOG_REQUEST";
export const ADD_BLOG_SUCCESS= "ADD_BLOG_SUCCESS";
export const ADD_BLOG_FAIL= "ADD_BLOG_FAIL";
export const ADMIN_ALL_BLOGS_REQUEST = "ADMIN_ALL_BLOGS_REQUEST";
export const ADMIN_ALL_BLOGS_SUCCESS = "ADMIN_ALL_BLOGS_SUCCESS";
export const ADMIN_ALL_BLOGS_FAIL = "ADMIN_ALL_BLOGS_FAIL";
export const ADMIN_UPDATE_BLOG_REQUEST = "ADMIN_UPDATE_BLOG_REQUEST";
export const ADMIN_UPDATE_BLOG_SUCCESS = "ADMIN_UPDATE_BLOG_SUCCESS";
export const ADMIN_UPDATE_BLOG_FAIL = "ADMIN_UPDATE_BLOG_FAIL";
export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCESS = "DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";
export const DELETE_BLOG_RESET = "DELETE_BLOG_RESET";
export const BLOG_COMMENT_REQUEST = "BLOG_COMMENT_REQUEST";
export const BLOG_COMMENT_SUCCESS = "BLOG_COMMENT_SUCCESS";
export const BLOG_COMMENT_FAIL = "BLOG_COMMENT_FAIL";
export const BLOG_COMMENT_RESET = "BLOG_COMMENT_RESET";


