export const ADD_TO_CART= "ADD_TO_CART";
export const REMOVE_CART_ITEM= "REMOVE_CART_ITEM";
export const SAVE_SHIPPING_ADDRESS= "SAVE_SHIPPING_ADDRESS";
export const CLEAR_CART= "CLEAR_CART";
export const BUY_NOW = "BUY_NOW";
export const REMOVE_BUY_NOW = "REMOVE_BUY_NOW";